set(SRCLIST_COMMON_H src/xCommonDefSPNG.h)
set(SRCLIST_COMMON_C                     )

set(SRCLIST_SEQPNG_H src/xSeqPNG.h  )
set(SRCLIST_SEQPNG_C src/xSeqPNG.cpp)

set(SRCLIST_PUBLIC  ${SRCLIST_COMMON_H} ${SRCLIST_SEQPNG_H} )
set(SRCLIST_PRIVATE ${SRCLIST_COMMON_C} ${SRCLIST_SEQPNG_C} )

target_sources(${PROJECT_NAME} PRIVATE ${SRCLIST_PRIVATE} PUBLIC ${SRCLIST_PUBLIC})
source_group(Common  FILES ${SRCLIST_COMMON_H} ${SRCLIST_COMMON_C})
source_group(SEQPNG  FILES ${SRCLIST_SEQPNG_H} ${SRCLIST_SEQPNG_C})










