mkdir buildD
cmake --build buildD --target clean
cmake -S ./ -B buildD -DPMBB_GENERATE_TESTING:BOOL=True -DPMBB_BUILD_WITH_MARCH_NATIVE:BOOL=True -DPMBB_GENERATE_MULTI_MICROARCH_LEVEL_BINARIES:BOOL=False
pause