set(SRCLIST_COMMON_H src/xCommonDefSLST.h)
set(SRCLIST_COMMON_C                     )

set(SRCLIST_SEQLST_H src/xSeqLST.h  )
set(SRCLIST_SEQLST_C src/xSeqLST.cpp)

set(SRCLIST_PUBLIC  ${SRCLIST_COMMON_H} ${SRCLIST_SEQLST_H} )
set(SRCLIST_PRIVATE ${SRCLIST_COMMON_C} ${SRCLIST_SEQLST_C} )

target_sources(${PROJECT_NAME} PRIVATE ${SRCLIST_PRIVATE} PUBLIC ${SRCLIST_PUBLIC})
source_group(Common  FILES ${SRCLIST_COMMON_H} ${SRCLIST_COMMON_C})
source_group(SEQLST  FILES ${SRCLIST_SEQLST_H} ${SRCLIST_SEQLST_C})










