#=========================================================================================================================================
# Utils
#=========================================================================================================================================
macro(PMBB_ASSIGN_AS_BOOL var)
  if(${ARGN})
    set(${var} TRUE)
  else()
    set(${var} FALSE)
  endif()
endmacro()

#=========================================================================================================================================
# common macros
#=========================================================================================================================================
macro(PMBB_setup_project_common)
  target_compile_features   (${PROJECT_NAME} PRIVATE cxx_std_17)
  target_compile_definitions(${PROJECT_NAME} PRIVATE X_PMBB_EXPERIMENTAL=${PMBB_ENABLE_EXPERIMENTAL_VALUE})
  target_include_directories(${PROJECT_NAME} PRIVATE ${fmtlib_SOURCE_DIR}/include)
endmacro()

#=========================================================================================================================================
# library macros
#=========================================================================================================================================
macro(PMBB_setup_lib_common_default)
  project("${LIB_CURRENT_NAME}")
  add_library(${PROJECT_NAME} OBJECT "")
  include(./TargetSources.cmake)
  PMBB_setup_project_common()
  foreach(DEP ${LIB_DEPENDENCIES})
    target_include_directories(${PROJECT_NAME} PRIVATE ${${DEP}_SOURCE_DIR}/src)    
  endforeach()
endmacro()
#-----------------------------------------------------------------------------------------------------------------------------------------
macro(PMBB_setup_lib_common_multiarch_per_arch)
  determine_compiler_settings_for_MFL(MFL_CO MFL_CD MFL_CN ${MFL})
  project("${LIB_CURRENT_NAME}_${MFL_CN}") 
  add_library(${PROJECT_NAME} OBJECT "")
  include(./TargetSources.cmake)
  PMBB_setup_project_common()
  target_compile_options    (${PROJECT_NAME} PRIVATE ${MFL_CO})
  target_compile_definitions(${PROJECT_NAME} PRIVATE ${MFL_CD})
  target_compile_definitions(${PROJECT_NAME} PRIVATE "PMBB_NAMESPACE=PMBB::${MFL_CN}")
  foreach(DEP ${LIB_DEPENDENCIES})
    target_include_directories(${PROJECT_NAME} PRIVATE ${${DEP}_SOURCE_DIR}/src)    
  endforeach()
endmacro()
#-----------------------------------------------------------------------------------------------------------------------------------------
macro(PMBB_setup_lib_common_multiarch_combined)
  project("${LIB_CURRENT_NAME}")
  add_library(${PROJECT_NAME} INTERFACE)
  foreach(MFL ${LIST_MFL})
    determine_compile_name_for_MFL(MFL_CN ${MFL})
    target_link_libraries(${PROJECT_NAME} INTERFACE ${LIB_CURRENT_NAME}_${MFL_CN} $<TARGET_OBJECTS:${LIB_CURRENT_NAME}_${MFL_CN}>)
  endforeach()
endmacro()
#-----------------------------------------------------------------------------------------------------------------------------------------
macro(PMBB_setup_lib_common_multiarch)
  foreach(MFL ${LIST_MFL})
    PMBB_setup_lib_common_multiarch_per_arch()
  endforeach()
  PMBB_setup_lib_common_multiarch_combined()
endmacro()
#-----------------------------------------------------------------------------------------------------------------------------------------
macro(PMBB_setup_lib_test)
  set(LIB_DEPENDENCIES_REV "${LIB_DEPENDENCIES}")
  list(REVERSE LIB_DEPENDENCIES_REV)

  foreach(TEST_NAME ${LIST_TESTS})
    project (${LIB_CURRENT_NAME}-TEST-${TEST_NAME})
    add_executable(${PROJECT_NAME} "")
    target_sources(${PROJECT_NAME} PRIVATE "test/test-${TEST_NAME}.cpp" )
    target_compile_features   (${PROJECT_NAME} PRIVATE cxx_std_17)
    target_compile_definitions(${PROJECT_NAME} PRIVATE X_PMBB_EXPERIMENTAL=${PMBB_ENABLE_EXPERIMENTAL_VALUE})
    target_include_directories(${PROJECT_NAME} PRIVATE ${doctest_SOURCE_DIR})
    target_include_directories(${PROJECT_NAME} PRIVATE ${fmtlib_SOURCE_DIR}/include)
    foreach(DEP ${LIB_DEPENDENCIES})
      target_include_directories(${PROJECT_NAME} PRIVATE ${${DEP}_SOURCE_DIR}/src)    
    endforeach()
    target_include_directories(${PROJECT_NAME} PRIVATE ${${LIB_CURRENT_NAME}_SOURCE_DIR}/src)
    target_link_libraries     (${PROJECT_NAME} PRIVATE ${LIB_CURRENT_NAME} )
    foreach(DEP ${LIB_DEPENDENCIES_REV})
      target_link_libraries(${PROJECT_NAME} PRIVATE ${DEP} )
    endforeach()
    target_link_libraries(${PROJECT_NAME} PRIVATE fmt::fmt Threads::Threads)
    add_test(NAME ${PROJECT_NAME} COMMAND ${PROJECT_NAME})
  endforeach()
endmacro()
#=========================================================================================================================================
# application macros
#=========================================================================================================================================
macro(PMBB_setup_app_common_default)
  set(APP_DEPENDENCIES_REV "${APP_DEPENDENCIES}")
  list(REVERSE APP_DEPENDENCIES_REV)

  project("${APP_NAME}")
  add_executable(${PROJECT_NAME} "")
  include(./TargetSources.cmake)
  PMBB_setup_project_common()
  #source_group("Source Files" FILES ${PROJECT_SOURCES})  

  foreach(DEP ${APP_DEPENDENCIES})
    target_include_directories(${PROJECT_NAME} PRIVATE ${${DEP}_SOURCE_DIR}/src)    
  endforeach()
  foreach(DEP ${APP_DEPENDENCIES_REV})
    target_link_libraries(${PROJECT_NAME} PRIVATE "${DEP}" )
  endforeach()
  if(DEFINED APP_THIRD_PARTY)
    foreach(DEP ${APP_THIRD_PARTY})
      target_link_libraries(${PROJECT_NAME} PRIVATE "${DEP}" )
    endforeach()
  endif()
  target_link_libraries(${PROJECT_NAME} PRIVATE fmt::fmt Threads::Threads)
endmacro()
#-----------------------------------------------------------------------------------------------------------------------------------------
macro(PMBB_setup_app_common_multiarch)
  set(APP_DEPENDENCIES_REV "${APP_DEPENDENCIES}")
  list(REVERSE APP_DEPENDENCIES_REV)

  foreach(MFL ${LIST_MFL})
    determine_compiler_settings_for_MFL(MFL_CO MFL_CD MFL_CN ${MFL})
    project("${APP_NAME}_MAIN_${MFL_CN}")       
    add_library(${PROJECT_NAME} OBJECT "")
    include(./TargetSources.cmake)
    source_group("Source Files" FILES ${PROJECT_SOURCES})
    
    target_compile_features   (${PROJECT_NAME} PRIVATE cxx_std_17)
    target_compile_definitions(${PROJECT_NAME} PRIVATE X_PMBB_EXPERIMENTAL=${PMBB_ENABLE_EXPERIMENTAL_VALUE})
    target_compile_options    (${PROJECT_NAME} PRIVATE ${MFL_CO})
    target_compile_definitions(${PROJECT_NAME} PRIVATE ${MFL_CD})
    target_compile_definitions(${PROJECT_NAME} PRIVATE "PMBB_NAMESPACE=PMBB::${MFL_CN}")
    target_compile_definitions(${PROJECT_NAME} PRIVATE "APP_MAIN=main_${MFL_CN}")
    target_include_directories(${PROJECT_NAME} PRIVATE ${fmtlib_SOURCE_DIR}/include)
    foreach(DEP ${APP_DEPENDENCIES})
      target_include_directories(${PROJECT_NAME} PRIVATE ${${DEP}_SOURCE_DIR}/src)    
    endforeach()

  endforeach()
  project("${APP_NAME}") 
  add_executable(${PROJECT_NAME} "")
  target_sources(${PROJECT_NAME} PRIVATE src/main_Dispatch.cpp)
  target_compile_features   (${PROJECT_NAME} PRIVATE cxx_std_17)
  target_compile_definitions(${PROJECT_NAME} PRIVATE X_PMBB_EXPERIMENTAL=${PMBB_ENABLE_EXPERIMENTAL_VALUE})
  target_include_directories(${PROJECT_NAME} PRIVATE ${fmtlib_SOURCE_DIR}/include)
  foreach(DEP ${APP_DEPENDENCIES})
    target_include_directories(${PROJECT_NAME} PRIVATE ${${DEP}_SOURCE_DIR}/src)    
  endforeach()
  target_include_directories(${PROJECT_NAME} PRIVATE ${${LIB_PMBB_DISPATCH_NAME}_SOURCE_DIR}/src)
  foreach(DEP ${APP_DEPENDENCIES_REV})
    target_link_libraries(${PROJECT_NAME} PRIVATE ${DEP} )
  endforeach()
  target_link_libraries     (${PROJECT_NAME} PRIVATE ${LIB_PMBB_DISPATCH_NAME} )
  foreach(MFL ${LIST_MFL})
    determine_compiler_settings_for_MFL(MFL_CO MFL_CD MFL_CN ${MFL})
    target_compile_definitions(${PROJECT_NAME} PRIVATE "BUILD_WITH_${MFL_CN}")
    target_link_libraries     (${PROJECT_NAME} PRIVATE "${APP_NAME}_MAIN_${MFL_CN}" )
  endforeach()
  if(DEFINED APP_THIRD_PARTY)
    foreach(DEP ${APP_THIRD_PARTY})
      target_link_libraries(${PROJECT_NAME} PRIVATE "${DEP}")
    endforeach()
  endif()
  target_link_libraries(${PROJECT_NAME} PRIVATE fmt::fmt Threads::Threads)
endmacro()
#-----------------------------------------------------------------------------------------------------------------------------------------
macro(PMBB_setup_app_common_dedicated)
  set(APP_DEPENDENCIES_REV "${APP_DEPENDENCIES}")
  list(REVERSE APP_DEPENDENCIES_REV)

  foreach(MFL ${LIST_MFL})
    determine_compiler_settings_for_MFL(MFL_CO MFL_CD MFL_CN ${MFL})
    project("${APP_NAME}_${MFL_CN}") 
    
    add_executable(${PROJECT_NAME} "")
    include(./TargetSources.cmake)
    source_group("Source Files" FILES ${PROJECT_SOURCES})
  
    target_compile_features   (${PROJECT_NAME} PRIVATE cxx_std_17)
    target_compile_definitions(${PROJECT_NAME} PRIVATE X_PMBB_EXPERIMENTAL=${PMBB_ENABLE_EXPERIMENTAL_VALUE})
    target_compile_options    (${PROJECT_NAME} PRIVATE ${MFL_CO})
    target_compile_definitions(${PROJECT_NAME} PRIVATE ${MFL_CD})
    target_compile_definitions(${PROJECT_NAME} PRIVATE "PMBB_NAMESPACE=PMBB::${MFL_CN}")
    target_include_directories(${PROJECT_NAME} PRIVATE ${fmtlib_SOURCE_DIR}/include)
    foreach(DEP ${APP_DEPENDENCIES})
      target_include_directories(${PROJECT_NAME} PRIVATE ${${DEP}_SOURCE_DIR}/src)    
    endforeach()
    foreach(DEP ${APP_DEPENDENCIES_REV})
      if(DEFINED ${DEP}_${MFL_CN}_BINARY_DIR)
        target_link_libraries(${PROJECT_NAME} PRIVATE "${DEP}_${MFL_CN}")
      else()
        target_link_libraries(${PROJECT_NAME} PRIVATE "${DEP}")
      endif()
    endforeach()
    if(DEFINED APP_THIRD_PARTY)
      foreach(DEP ${APP_THIRD_PARTY})
        target_link_libraries(${PROJECT_NAME} PRIVATE "${DEP}")
      endforeach()
    endif()
    target_link_libraries     (${PROJECT_NAME} PRIVATE fmt::fmt Threads::Threads)
  endforeach()
endmacro()
